version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - aws --version
  build:
    commands:
      - echo "Build phase"
      - cd backend
      - echo "In backend directory"
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Build completed"

artifacts:
  files:
    - appspec.yml
    - taskdef.json 